// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqmhiuvpvxssnkbtmdgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxbWhpdXZwdnhzc25rYnRtZGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Mzg2MzcsImV4cCI6MjA3MjIxNDYzN30.LWLlvHCHclHmsexk90p3-hZEplEuk8wEj5ftOW7qKjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});